### PR TITLE
Newpr44

### PR DESCRIPTION
**Pull request by bobsmith1**

### CODE REVIEW

**Comment by davidx** [comment]
Thanks! @bobsmith1

**Comment by davidx** [comment]
``` ---
minimum_reviewers: 0
before:
- sudo apt-get update
- sudo apt-get install apt-transport-https ca-certificates
build_steps:
- make test
merge: true
```

**Comment by davidx** [comment]
<p>Build Status: Looks like there's an issue with build step make_test !  :cloud: </p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:19
> Duration: 2 seconds.
> Result:  OK
> Message: Merge Success: bd39826f7afe2aea0df2171125f85711ede635f7 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/207e429d0eec39099ff35a8c6e2bca1c">[GIST]</a>
> </p>

```



Updating e74de3a..bd39826
Fast-forward (no commit created; -m option ignored)
 .thumbs.yml |  7 +++++++
 README.md   | 10 +++++++++-
 2 files changed, 16 insertions(+), 1 deletion(-)
 create mode 100644 .thumbs.yml

```

---

</details>

<details>
 <summary>

:no_entry: MAKE_TEST   ERROR </summary>



 <p>

> Started at: 2016-09-01 17:19
> Duration: 0 seconds.
> Result:  ERROR
> Message: Step make_test Failed!
> Exit Code:  2
> <a href="https://gist.github.com/a35b5915d9e83f82cb16fa0fb0877dcf">[GIST]</a>
> </p>

```

cd /tmp/thumbs/davidx_example_repo_3 && make test 2>&1

make: *** No rule to make target `test'.  Stop.


```

---

</details>

**Comment by bobsmith1** [comment]
hi

**Comment by davidx** [comment]
``` ---
minimum_reviewers: 0
before:
- sudo apt-get update
- sudo apt-get install apt-transport-https ca-certificates
build_steps:
- make test
merge: true
```

**Comment by davidx** [comment]
<p>Build Status: Looks like there's an issue with build step make_test !  :cloud: </p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:21
> Duration: 2 seconds.
> Result:  OK
> Message: Merge Success: bd39826f7afe2aea0df2171125f85711ede635f7 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/29c311dfe64fbb09d010801009de7085">[GIST]</a>
> </p>

```



Updating e74de3a..bd39826
Fast-forward (no commit created; -m option ignored)
 .thumbs.yml |  7 +++++++
 README.md   | 10 +++++++++-
 2 files changed, 16 insertions(+), 1 deletion(-)
 create mode 100644 .thumbs.yml

```

---

</details>

<details>
 <summary>

:no_entry: MAKE_TEST   ERROR </summary>



 <p>

> Started at: 2016-09-01 17:21
> Duration: 0 seconds.
> Result:  ERROR
> Message: Step make_test Failed!
> Exit Code:  2
> <a href="https://gist.github.com/55265fc016c62a3665cf909d0bb7658f">[GIST]</a>
> </p>

```

cd /tmp/thumbs/davidx_example_repo_3 && make test 2>&1

make: *** No rule to make target `test'.  Stop.


```

---

</details>

**Comment by davidx** [comment]
Build not valid for merge.

**Comment by davidx** [comment]
``` ---
minimum_reviewers: 0
before:
- sudo apt-get update
- sudo apt-get install apt-transport-https ca-certificates
build_steps:
- uptime
merge: true
```

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:22
> Duration: 3 seconds.
> Result:  OK
> Message: Merge Success: 34504737c1c2641c5e29084fb4e0fc5294d6b30e onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/0f60599422451bda26ba5212da26a0e6">[GIST]</a>
> </p>

```



Updating e74de3a..3450473
Fast-forward (no commit created; -m option ignored)
 .thumbs.yml |  7 +++++++
 README.md   | 10 +++++++++-
 2 files changed, 16 insertions(+), 1 deletion(-)
 create mode 100644 .thumbs.yml

```

---

</details>

<details>
 <summary>

:white_check_mark: UPTIME   OK </summary>



 <p>

> Started at: 2016-09-01 17:22
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0
> <a href="https://gist.github.com/0422c77c1d9c5d072fbcc281c7b011d2">[GIST]</a>
> </p>

```

cd /tmp/thumbs/davidx_example_repo_3 && uptime 2>&1

17:22  up 6 days,  7:29, 9 users, load averages: 1.87 1.76 1.67


```

---

</details>

**Comment by davidx** [comment]
Successfully merged _davidx/example_repo/pulls/3_ (_34504737c1c2641c5e29084fb4e0fc5294d6b30e_ on to _master_)

``` yaml
---
:sha: d392aa7c58d82c68f5087a456295a5478504a149
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
