### PR TITLE
Newpr33

### PR DESCRIPTION
**Pull request by davidx**

### CODE REVIEW

**Comment by davidx** [comment]
hi

**Comment by davidx** [comment]
hi

**Comment by davidx** [comment]
yah ?

**Comment by davidx** [comment]
yah ?

**Comment by davidx** [comment]
`@thumb_config.to_yaml`

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 16:56
> Duration: 4 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/65685d480cfa0cb9fd4f20ba4f40e781">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
`@thumb_config.to_yaml`

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 16:57
> Duration: 5 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/fa9d41b9e2b9ad205a09b58c45aa01a6">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
`@thumb_config.to_yaml`

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 16:57
> Duration: 5 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/ec1c002350e9eac2de8dd288c8a3026f">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
`@thumb_config.to_yaml`

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 16:57
> Duration: 5 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/7478ce0e94ab81debc5878510c4a2320">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
`@thumb_config.to_yaml`

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 16:57
> Duration: 7 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/51735a2fc6af508ca7bead16ee981b93">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
`@thumb_config.to_yaml`

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 16:57
> Duration: 4 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/35edfc8075330b087753b2892ecf71e5">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
`@thumb_config.to_yaml`

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 16:58
> Duration: 5 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/28a425780499c8294437560c60330e7f">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
hi

**Comment by davidx** [comment]
``` ---
...
```

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:02
> Duration: 2 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/fbf5fb29010f70dfacf3b19721ed9f2d">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
<p>Build Status: Looks like there's an issue with build step merge !  :cloud: </p>

<details>
 <summary>

:no_entry: MERGE   ERROR </summary>



 <p>

> Started at: 2016-09-01 17:02
> Duration:  seconds.
> Result:  ERROR
> Message: Merge test failed
> Exit Code:  ERROR
> <a href="https://gist.github.com/b3a515910596300b778a2ce9dfaccb9a">[GIST]</a>
> </p>

```



#<NoMethodError: undefined method `>' for nil:NilClass>

```

---

</details>

**Comment by davidx** [comment]
Build not valid for merge.

**Comment by davidx** [comment]
yah?

**Comment by davidx** [comment]
``` ---
...
```

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:09
> Duration: 2 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/a9eeae52095695336c0826db738dc72d">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
Build not valid for merge.

**Comment by davidx** [comment]
<p>Build Status: Looks like there's an issue with build step merge !  :cloud: </p>

<details>
 <summary>

:no_entry: MERGE   ERROR </summary>



 <p>

> Started at: 2016-09-01 17:09
> Duration:  seconds.
> Result:  ERROR
> Message: Merge test failed
> Exit Code:  ERROR
> <a href="https://gist.github.com/4311e9cad7a5103e8d6eeafde9493199">[GIST]</a>
> </p>

```



#<Git::GitExecuteError: git  clone '--' 'git@github.com:davidx/example_repo' '/tmp/thumbs/davidx_example_repo_2'  2>&1:Cloning into '/tmp/thumbs/davidx_example_repo_2'...
error: could not lock config file /private/tmp/thumbs/davidx_example_repo_2/.git/config: No such file or directory
fatal: Could not set 'remote.origin.fetch' to '+refs/heads/*:refs/remotes/origin/*'>

```

---

</details>

**Comment by davidx** [comment]
Build not valid for merge.

**Comment by davidx** [comment]
<p>Build Status: Looks like there's an issue with build step merge !  :cloud: </p>

<details>
 <summary>

:no_entry: MERGE   ERROR </summary>



 <p>

> Started at: 2016-09-01 17:09
> Duration:  seconds.
> Result:  ERROR
> Message: Merge test failed
> Exit Code:  ERROR
> <a href="https://gist.github.com/ae7e13d7c11f9a6bd785b03833e6aaeb">[GIST]</a>
> </p>

```



#<Git::GitExecuteError: git  clone '--' 'git@github.com:davidx/example_repo' '/tmp/thumbs/davidx_example_repo_2'  2>&1:Cloning into '/tmp/thumbs/davidx_example_repo_2'...
error: could not lock config file /private/tmp/thumbs/davidx_example_repo_2/.git/config: No such file or directory
fatal: Could not set 'remote.origin.fetch' to '+refs/heads/*:refs/remotes/origin/*'>

```

---

</details>

**Comment by davidx** [comment]
Build not valid for merge.

**Comment by davidx** [comment]
``` ---
...
```

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:09
> Duration: 2 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/6a5aa2dcef06af6be72da73987e050c7">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
y

**Comment by davidx** [comment]
ss

**Comment by davidx** [comment]
sas

**Comment by bobsmith1** [comment]
hi

**Comment by davidx** [comment]
``` ---
...
```

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:17
> Duration: 2 seconds.
> Result:  OK
> Message: Merge Success: 82cdfe3de248bae0a2b084cbd0034906405b7864 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/4a7c3e17853b855aaf3dd7b4ab82251b">[GIST]</a>
> </p>

```



Updating e74de3a..82cdfe3
Fast-forward (no commit created; -m option ignored)
 README.md | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

```

---

</details>

**Comment by davidx** [comment]
Build not valid for merge.

**Pull request merged**
