### PR TITLE
thumbs

### PR DESCRIPTION
**Pull request by bobsmith1**

### CODE REVIEW

**Comment by davidx** [comment]
Thanks! @bobsmith1

**Comment by davidx** [comment]
``` ---
minimum_reviewers: 1
before:
- sudo apt-get update
- sudo apt-get install apt-transport-https ca-certificates
build_steps:
- uptime
merge: true
```

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:42
> Duration: 1 seconds.
> Result:  OK
> Message: Merge Success: ba135930fb50cace90cc85eb712aa9e7de428a67 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/11948ba6d7180bc40126df0d4c4e6afc">[GIST]</a>
> </p>

```



Merge made by the 'recursive' strategy.
 .thumbs.yml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

</details>

<details>
 <summary>

:white_check_mark: UPTIME   OK </summary>



 <p>

> Started at: 2016-09-01 17:42
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0
> <a href="https://gist.github.com/6a729d96496fbe9b3d9ed24413a613d2">[GIST]</a>
> </p>

```

cd /tmp/thumbs/davidx_example_repo_7 && uptime 2>&1

17:42  up 6 days,  7:49, 9 users, load averages: 1.77 1.75 1.69


```

---

</details>

**Comment by davidx** [comment]
Waiting for at least 1 reviews

**Comment by bobsmith1** [comment]
+1

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:42
> Duration: 2 seconds.
> Result:  OK
> Message: Merge Success: ba135930fb50cace90cc85eb712aa9e7de428a67 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/a77e49cc4262f382668647db69ba7a67">[GIST]</a>
> </p>

```



Merge made by the 'recursive' strategy.
 .thumbs.yml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

</details>

<details>
 <summary>

:white_check_mark: UPTIME   OK </summary>



 <p>

> Started at: 2016-09-01 17:42
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0
> <a href="https://gist.github.com/38c2d69646b804c287cd71368f432cda">[GIST]</a>
> </p>

```

cd /tmp/thumbs/davidx_example_repo_7 && uptime 2>&1

17:42  up 6 days,  7:49, 9 users, load averages: 1.72 1.73 1.69


```

---

</details>

**Comment by davidx** [comment]
Not

**Comment by davidx** [comment]
Build not valid for merge.

**Comment by bobsmith1** [comment]
howboutnow ?

**Comment by bobsmith1** [comment]
hi

**Comment by davidpuddy1** [comment]
hi

**Comment by davidpuddy1** [comment]
hi

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 19:48
> Duration: 1 seconds.
> Result:  OK
> Message: Merge Success: ba135930fb50cace90cc85eb712aa9e7de428a67 onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/f26e47697086253d1443db8ba8221937">[GIST]</a>
> </p>

```



Merge made by the 'recursive' strategy.
 .thumbs.yml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

</details>

<details>
 <summary>

:white_check_mark: UPTIME   OK </summary>



 <p>

> Started at: 2016-09-01 19:48
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0
> <a href="https://gist.github.com/053ff7a9dc95882df7fb4c4855bce4ac">[GIST]</a>
> </p>

```

cd /tmp/thumbs/davidx_example_repo_7 && uptime 2>&1

19:48  up 6 days,  9:55, 9 users, load averages: 1.73 1.78 1.82


```

---

</details>

**Comment by davidx** [comment]
Not enough code reviews

**Comment by davidx** [comment]
Build not valid for merge.

**Comment by davidpuddy1** [comment]
hi

**Comment by davidpuddy1** [comment]
test

**Pull request merged**
