### PR TITLE
Newpr56

### PR DESCRIPTION
**Pull request by bobsmith1**

### CODE REVIEW

**Comment by davidx** [comment]
Thanks! @bobsmith1

**Comment by davidx** [comment]
``` ---
minimum_reviewers: 0
before:
- sudo apt-get update
- sudo apt-get install apt-transport-https ca-certificates
build_steps:
- uptime
merge: true
```

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:26
> Duration: 1 seconds.
> Result:  OK
> Message: Merge Success: 7c563aaefcf5cd1c7e772567f5ff3c5cd2f28d8d onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/f92257770a17160ef7ffdd077b739dba">[GIST]</a>
> </p>

```



Merge made by the 'recursive' strategy.
 README.md | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

```

---

</details>

<details>
 <summary>

:white_check_mark: UPTIME   OK </summary>



 <p>

> Started at: 2016-09-01 17:26
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0
> <a href="https://gist.github.com/c1074b4500f9979553e1a942ba64fd6b">[GIST]</a>
> </p>

```

cd /tmp/thumbs/davidx_example_repo_4 && uptime 2>&1

17:26  up 6 days,  7:33, 9 users, load averages: 1.81 1.80 1.70


```

---

</details>

**Comment by bobsmith1** [comment]
looks nice

**Comment by davidx** [comment]
<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK </summary>



 <p>

> Started at: 2016-09-01 17:26
> Duration: 1 seconds.
> Result:  OK
> Message: Merge Success: 7c563aaefcf5cd1c7e772567f5ff3c5cd2f28d8d onto target branch: master
> Exit Code:  OK
> <a href="https://gist.github.com/935863d4e496e5b9216287702ea32b03">[GIST]</a>
> </p>

```



Merge made by the 'recursive' strategy.
 README.md | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

```

---

</details>

<details>
 <summary>

:white_check_mark: UPTIME   OK </summary>



 <p>

> Started at: 2016-09-01 17:26
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0
> <a href="https://gist.github.com/f0daa03d4ba6f180a0004fb4ecd20d21">[GIST]</a>
> </p>

```

cd /tmp/thumbs/davidx_example_repo_4 && uptime 2>&1

17:26  up 6 days,  7:33, 9 users, load averages: 1.76 1.79 1.70


```

---

</details>

**Comment by davidx** [comment]
Merging and closing this pr

**Comment by davidx** [comment]
Successfully merged _davidx/example_repo/pulls/4_ (_7c563aaefcf5cd1c7e772567f5ff3c5cd2f28d8d_ on to _master_)

``` yaml
---
:sha: a2039d4e17fbc458df21ad11ff3aae8b2e0f6ea9
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
